In [33]:
import pandas as pd
import numpy as np
import os

In [34]:
df = pd.read_csv('../data\\raw/IMDB Dataset.csv')

In [35]:
df.shape

(50000, 2)

In [36]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

## Lowercase

In [37]:
df['review'] = df['review'].str.lower()
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

## Remove html

In [38]:
import re
def remove_html(text):
    pattern =  re.compile('<.*?>')
    return pattern.sub(r'', text)
df['review'] = df['review'].apply(remove_html)
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

## Remove url

In [39]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)
df['review'] = df['review'].apply(remove_url)
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

## Remove Mention

In [40]:
def remove_mention(text):
    pattern = re.compile(r'(?<!\w)@\w+')
    return pattern.sub(r'', text)
df['review'] = df['review'].apply(remove_mention)
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

## Remove hashtag

In [41]:
def remove_hashtag(text):
    pattern = re.compile(r'(?<!\w)#\w+')
    return pattern.sub(r'', text)
df['review'] = df['review'].apply(remove_hashtag)
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

## Remove special characters

In [42]:
def remove_special_characters(text, keep_apostrophe=True):
    # Keep letters/spaces; optionally keep apostrophes in words like don't.
    if keep_apostrophe:
        pattern = re.compile(r"[^\w\s']")
    else:
        pattern = re.compile(r'[^\w\s]')
    return pattern.sub('', text)

df['review'] = df['review'].apply(remove_special_characters)
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production the filming tech...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's love in the time of money is a...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

## Remove numbers (conditional)

In [43]:
def remove_numbers(text, mode='standalone'):
    # mode='standalone': remove tokens that are only digits (e.g., 2024, 10/10 -> 10 parts).
    # mode='all': remove every digit character, including inside words (movie2 -> movie).
    if mode == 'all':
        pattern = re.compile(r'\d+')
    else:
        pattern = re.compile(r'\b\d+\b')
    return pattern.sub('', text)

# Change mode to 'all' if you want to remove every digit character.
df['review'] = df['review'].apply(lambda x: remove_numbers(x, mode='standalone'))
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production the filming tech...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's love in the time of money is a...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

## Normalize whitespace

In [44]:
def normalize_whitespace(text):
    # Replace repeated spaces/newlines/tabs with a single space, then trim.
    return re.sub(r'\s+', ' ', text).strip()

df['review'] = df['review'].apply(normalize_whitespace)
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production the filming tech...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's love in the time of money is a...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

## Pipeline evaluation report

In [46]:
# Rebuild from raw text to evaluate each preprocessing step quantitatively.
df_eval = pd.read_csv('../data\\raw/IMDB Dataset.csv').copy()
df_eval['review_raw'] = df_eval['review'].astype(str)

def tokenize(series):
    return series.str.split()

def vocab_set(series):
    tokens = tokenize(series).explode().dropna()
    return set(tokens.tolist())

def length_stats(series):
    word_len = tokenize(series).str.len()
    char_len = series.str.len()
    return {
        'doc_count': int(series.shape[0]),
        'word_len_mean': float(word_len.mean()),
        'word_len_median': float(word_len.median()),
        'word_len_p90': float(word_len.quantile(0.9)),
        'char_len_mean': float(char_len.mean()),
        'char_len_median': float(char_len.median()),
        'char_len_p90': float(char_len.quantile(0.9)),
    }

def vocab_change_ratio(prev_series, curr_series):
    prev_vocab = vocab_set(prev_series)
    curr_vocab = vocab_set(curr_series)
    if len(prev_vocab) == 0:
        return {'prev_vocab_size': 0, 'curr_vocab_size': len(curr_vocab), 'vocab_change_ratio': 0.0}
    overlap = len(prev_vocab & curr_vocab)
    changed_ratio = 1 - (overlap / len(prev_vocab))
    return {
        'prev_vocab_size': len(prev_vocab),
        'curr_vocab_size': len(curr_vocab),
        'vocab_change_ratio': float(changed_ratio),
    }

steps = [
    ('lowercase', lambda s: s.str.lower()),
    ('remove_html', lambda s: s.apply(remove_html)),
    ('remove_url', lambda s: s.apply(remove_url)),
    ('remove_mention', lambda s: s.apply(remove_mention)),
    ('remove_hashtag', lambda s: s.apply(remove_hashtag)),
    ('remove_special_characters', lambda s: s.apply(lambda x: remove_special_characters(x, keep_apostrophe=True))),
    ('remove_numbers_standalone', lambda s: s.apply(lambda x: remove_numbers(x, mode='standalone'))),
    ('normalize_whitespace', lambda s: s.apply(normalize_whitespace)),
]

report_rows = []
prev_name = 'raw'
prev_series = df_eval['review_raw'].copy()
report_rows.append({
    'step': prev_name,
    'prev_vocab_size': np.nan,
    'curr_vocab_size': len(vocab_set(prev_series)),
    'vocab_change_ratio': np.nan,
    **length_stats(prev_series),
})

for step_name, step_func in steps:
    curr_series = step_func(prev_series)
    vocab_metrics = vocab_change_ratio(prev_series, curr_series)
    stats = length_stats(curr_series)
    report_rows.append({
        'step': step_name,
        **vocab_metrics,
        **stats,
    })
    prev_series = curr_series

report_df = pd.DataFrame(report_rows)
report_df['vocab_change_ratio'] = report_df['vocab_change_ratio'].round(4)
for col in ['word_len_mean', 'word_len_median', 'word_len_p90', 'char_len_mean', 'char_len_median', 'char_len_p90']:
    report_df[col] = report_df[col].round(2)

report_df

,step,prev_vocab_size,curr_vocab_size,vocab_change_ratio,doc_count,word_len_mean,word_len_median,word_len_p90,char_len_mean,char_len_median,char_len_p90
0,raw,NaN,438729,NaN,50000,231.16,173.0,451.0,1309.43,970.0,2581.0
1,lowercase,438729.0,390931,0.4418,50000,231.16,173.0,451.0,1309.43,970.0,2581.0
2,remove_html,390931.0,422479,0.0886,50000,227.11,170.0,443.0,1285.17,953.0,2528.0
3,remove_url,422479.0,422303,0.0004,50000,227.11,170.0,443.0,1285.03,953.0,2528.0
4,remove_mention,422303.0,422301,0.0000,50000,227.11,170.0,443.0,1285.03,953.0,2528.0
5,remove_hashtag,422301.0,422185,0.0004,50000,227.10,170.0,443.0,1285.01,953.0,2528.0
6,remove_special_characters,422185.0,236072,0.7519,50000,226.19,170.0,441.0,1249.79,927.0,2458.1
7,remove_numbers_standalone,236072.0,234035,0.0093,50000,225.20,169.0,439.0,1247.22,925.0,2454.1
8,normalize_whitespace,234035.0,234035,0.0000,50000,225.20,169.0,439.0,1245.28,923.0,2451.0

## Length distribution impact by step

In [47]:
impact_df = report_df.copy()
impact_df['word_len_mean_delta'] = impact_df['word_len_mean'].diff().round(2)
impact_df['word_len_p90_delta'] = impact_df['word_len_p90'].diff().round(2)
impact_df['char_len_mean_delta'] = impact_df['char_len_mean'].diff().round(2)
impact_df['char_len_p90_delta'] = impact_df['char_len_p90'].diff().round(2)

impact_df[[
    'step',
    'vocab_change_ratio',
    'word_len_mean', 'word_len_mean_delta',
    'word_len_p90', 'word_len_p90_delta',
    'char_len_mean', 'char_len_mean_delta',
    'char_len_p90', 'char_len_p90_delta'
]]

,step,vocab_change_ratio,word_len_mean,word_len_mean_delta,word_len_p90,word_len_p90_delta,char_len_mean,char_len_mean_delta,char_len_p90,char_len_p90_delta
0,raw,NaN,231.16,NaN,451.0,NaN,1309.43,NaN,2581.0,NaN
1,lowercase,0.4418,231.16,0.00,451.0,0.0,1309.43,0.00,2581.0,0.0
2,remove_html,0.0886,227.11,-4.05,443.0,-8.0,1285.17,-24.26,2528.0,-53.0
3,remove_url,0.0004,227.11,0.00,443.0,0.0,1285.03,-0.14,2528.0,0.0
4,remove_mention,0.0000,227.11,0.00,443.0,0.0,1285.03,0.00,2528.0,0.0
5,remove_hashtag,0.0004,227.10,-0.01,443.0,0.0,1285.01,-0.02,2528.0,0.0
6,remove_special_characters,0.7519,226.19,-0.91,441.0,-2.0,1249.79,-35.22,2458.1,-69.9
7,remove_numbers_standalone,0.0093,225.20,-0.99,439.0,-2.0,1247.22,-2.57,2454.1,-4.0
8,normalize_whitespace,0.0000,225.20,0.00,439.0,0.0,1245.28,-1.94,2451.0,-3.1